[versions]
androidGradlePlugin = "8.12.3"
kotlin = "2.2.20"
ksp = "2.3.2"
rust-android = "0.9.6"
androidxCore = "1.17.0"
androidxActivity = "1.11.0"
androidxBrowser = "1.9.0"
androidxBiometric = "1.1.0"
androidxDatastorePreferences = "1.1.7"
androidxRoom = "2.8.0"
androidxSqlite = "2.6.0"
androidxLifecycle = "2.9.4"
kotlinxSerialization = "1.9.0"
kotlinxCoroutines = "1.10.2"
androidxAppCompat = "1.7.1"
androidxSplashscreen = "1.0.1"
androidxCompose = "2025.01.01"
androidxGlance = "1.1.1"

[libraries]
android-tools-build-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

commons-io = { module = "commons-io:commons-io", version = "2.20.0" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-activity-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxActivity" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidxBrowser" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "androidxBiometric" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastorePreferences" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidxRoom" }
androidx-sqlite-ktx = { module = "androidx.sqlite:sqlite-ktx", version.ref = "androidxSqlite" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplashscreen" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxCompose" }
androidx-compose-m3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-junit = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-ext = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version = "1.11.0" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.9.4" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version = "2.10.4" }
androidx-glance = { module = "androidx.glance:glance", version.ref = "androidxGlance" }
androidx-glance-m3 = { module = "androidx.glance:glance-material3", version.ref = "androidxGlance" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidxGlance" }
androidx-glance-appwidget-preview = { module = "androidx.glance:glance-appwidget-preview", version.ref = "androidxGlance" }
androidx-glance-preview = { module = "androidx.glance:glance-preview", version.ref = "androidxGlance" }

androidx-test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version = "1.3.0" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.7.0" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.7.0" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-serlization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

conscrypt-android = { module = "org.conscrypt:conscrypt-android", version = "2.5.3" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.1.0" }
jna = { module = "net.java.dev.jna:jna", version = "5.18.0" }
junit = { module = "junit:junit", version = "4.13.2" }
robolectric = { module = "org.robolectric:robolectric", version = "4.16" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "6.0.0" }
mockito-inline = { module = "com.linkedin.dexmaker:dexmaker-mockito-inline-extended", version = "2.28.1" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.20.0" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version = "2.20.0" }
tutasdk = { module = "de.tutao:tutasdk", version = "unspecified" }

[plugins]
tutao-testconvention = { id = "de.tutao.testconvention", version = "unspecified" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
rust-android = { id = "org.mozilla.rust-android-gradle.rust-android", version.ref = "rust-android" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }