[package]
edition = "2021"
name = "tutao_node-mimimi"
version = "251.241030.0"

[lib]
# need to have lib to be able to use this from rust tests
crate-type = ["cdylib", "lib"]

[profile.release]
lto = true
strip = "symbols"


[dependencies]
tuta-sdk = { path = "../../tuta-sdk/rust/sdk", features = ["net"] }
async-trait = "0.1.83"
rand = { version = "0.8.5" }
mail-parser = { version = "0.9.4", features = ["full_encoding"] }
thiserror = { version = "1.0.64" }
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.16.12", default-features = false, features = ["napi9", "async", "tokio_rt"] }
napi-derive = { version = "2.16.12", optional = true }
base64 = "0.22.1"
log = { version = "0.4.22" }

# used for tuta-imap
serde = { version = "1.0.210", features = ["derive"] }
rustls = { version = "0.23.13", features = ["std"] }
regex = "1.11.1"

[dependencies.imap-codec]
git = "https://github.com/duesee/imap-codec.git"
rev = "16a5c182285c7a895b06276f68a116caf2cb294f"
features = ["serde", "starttls", "ext_id", "ext_metadata"]


[build-dependencies]
napi-build = { version = "2.1.3" }

[dev-dependencies]
base64 = "0.22.1"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
tuta-sdk = { path = "../../tuta-sdk/rust/sdk", features = ["net", "testing"] }
mail-builder = { version = "0.3.2" }

# tuta-imap
j4rs = { version = "0.20.0" }
lazy_static = { version = "0.2.11" }

[features]
default = ["javascript"]
# needed to turn off the autogenerated ffi when using the tests
javascript = ["dep:napi-derive"]