blank_issues_enabled: false
contact_links:
  - name: Discussions on Github
    url: https://github.com/tutao/tutanota/discussions/
    about: Good for feature requests and help with contributions
  - name: Forum
    url: https://www.reddit.com/r/tutanota/
    about: More general discussion and questions
  - name: Contact
    url: https://tuta.com/contact/
    about: Contact page